# [[headers]]
#   for = "/*"
#     [headers.values]
#     Access-Control-Allow-Origin = "*"
[[headers]]
  for = "/favicon/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[headers]]
  for = "/manifest.json"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[headers]]
  for = "*.js"
  [headers.values] # cache for 1 year
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.css"
  [headers.values] # cache for 1 year
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/*.(svg|jpg|jpeg|png|gif|webp|ico|ttf|ttc|otf|eot|woff|woff2)"
  [headers.values] # cache for 1 year
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Robots-Tag = "noindex"

[build]
  command = "npm run build --config astro.config.netlify.mjs"
  publish = "dist"
  edge_functions = "netlify/functions"

# [[edge_functions]]
#   function = "test"
#   path = "/test"

[context.develop]

[context.develop.processing.images]
  compress = true
[context.develop.processing.css]
  minify = true
[context.develop.processing.js]
  minify = true

[context.deploy-preview]

[context.deploy-preview.processing]
  skip_processing = true

# Netlify CLI
[dev]
  command = "npm run dev"
  port=80
  framework="#custom"
  targetPort=3030